version: '3'
services:
  db:
    image: mariadb
    container_name: bdpanaderia
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: panaderiaDB
      MYSQL_USER: panaderia
      MYSQL_PASSWORD: pswpanaderia
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3309:3306"